### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [NamedKitten/KittehPlayer#1]
```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-9991/AppRun)
/run/firejail/appimage/.appimage-9991/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-9991/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6.

Reference:
https://github.com/AppImage/appimage.github.io/pull/874

**Comment by NamedKitten** [comment]
Ugh, I guess I'll have to resort to building on old Ubuntu and manually compiling and installing mpv in order to get a new version. Thanks for the report, will use old Ubuntu.

**Comment by NamedKitten** [comment]
For now I recommend people who use incompatible libstdc++ versions to compile it from source using my appimage script after installing build dependencies which I will list in my README.

**Comment by probonopd** [comment]
Would it be possible to build on trusty rather than xenial?

**Comment by NamedKitten** [comment]
The latest Qt version https://launchpad.net/~beineri provides it too old for me. I would need to build Qt from scratch and I don't have the time for that.

**Comment by probonopd** [comment]
Are you sure? There is Qt 5.10.1 for /opt Trusty. Which one do you need?

**Comment by NamedKitten** [comment]
I'll give it a go.

**Comment by NamedKitten** [comment]
Try now~

**Comment by probonopd** [comment]
Works. Added to AppImageHub. Thank you.
