### ISSUE TITLE
Does not build with Qt 5.9

### ISSUE THREAD

**Issue by luigino** [NamedKitten/KittehPlayer#10]
Not all distros are bleeding edge. Is there a workaround for this:
``'
[ 92%] Building CXX object CMakeFiles/KittehPlayer.dir/KittehPlayer_autogen/mocs_compilation.cpp.o
/usr/bin/g++-8  -DDISABLE_MpvPlayerBackend -DENABLE_X11 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I"/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/build/KittehPlayer_autogen/include" -I"/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802" -I"/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/build" -I"/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/build/spdlog/include" -I/usr/include/qt5/QtGui/5.9.7 -I/usr/include/qt5/QtGui/5.9.7/QtGui -I/usr/include/qt5/QtCore/5.9.7 -I/usr/include/qt5/QtCore/5.9.7/QtCore -isystem /usr/include/qt5 -I/usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -DNDEBUG -O2 -g -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/KittehPlayer.dir/KittehPlayer_autogen/mocs_compilation.cpp.o -c "/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/build/KittehPlayer_autogen/mocs_compilation.cpp"
/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/src/utils.cpp: In function 'void Utils::checkForUpdates()':
/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/src/utils.cpp:68:11: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [17]')
   if (json["target_commitish"].toString().length() != 0) {
           ^
/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/src/utils.cpp:69:13: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [17]')
     if (json["target_commitish"].toString().endsWith(current_version) == 0) {
             ^
/home/abuild/rpmbuild/BUILD/KittehPlayer-0~git20181223.d816802/src/utils.cpp:72:13: error: no match for 'operator[]' (operand types are 'QJsonDocument' and 'const char [17]')
         json["target_commitish"].toString().toUtf8().constData());
             ^
```

**Comment by NamedKitten** [comment]
No plan of supporting old Qt, just use the provided appimages in releases.
I don't plan on supporting this codebase in the future, my contact information is on https://namedkitten.pw incase you want me to tell you when I rewrite this program.

**Comment by luigino** [comment]
I registered on your site, please keep me in the loop about future developments.

Regards
