### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by rohitghali** [NamedKitten/KittehPlayer#15]
No idea how to uninstall this program. I'm on Arch btw.

**Comment by NamedKitten** [comment]
How did you install it? AUR or manually?

**Comment by rohitghali** [comment]
Manually.

**Comment by NamedKitten** [comment]
`sudo rm /usr/bin/KittehPlayer /usr/share/applications/KittehPlayer.desktop /usr/share/icons/hicolor/256x256/apps/KittehPlayer.png`
